#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Market/Market.csproj", "Market/"]
COPY ["Market.DAL/Market.DAL.csproj", "Market.DAL/"]
COPY ["Market.Domain/Market.Domain.csproj", "Market.Domain/"]
COPY ["Market.Service/Market.Service.csproj", "Market.Service/"]
RUN dotnet restore "Market/Market.csproj"
COPY . .
WORKDIR "/src/Market"
RUN dotnet build "Market.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Market.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Market.dll"]